### ISSUE TITLE
AutoIt Error

### ISSUE THREAD

**Issue by sunih** [mhasanjb/ForceBindIP-Gui#11]
Everything seems ok, but i keep getting this error:
![image](https://user-images.githubusercontent.com/57396742/217877194-aa47d0db-d687-4d8b-92c3-04c30caa567e.png)
![image](https://user-images.githubusercontent.com/57396742/217877251-2c0e9236-b38b-4a34-b60b-251efa90836c.png)

**Comment by ixjb94** [comment]
@sunih Hi,
sorry for the delay.
the issue caused because of version conflicts.

You can download the new version:
[Force Bind IP](https://github.com/ixjb94/ForceBindIP-Gui/releases/download/binary/ForceBindIP.-.Gui.exe)

Thanks for the report.
