### ISSUE TITLE
Google Chrome dll injection registry file?

### ISSUE THREAD

**Issue by thrik** [mhasanjb/ForceBindIP-Gui#13]
Hello, I use Brave Browser. I assume the method you listed will also work for Brave since it's based on Chrome. 

However, in the section listed, it refers to a registry file. I do not see a link to said file. Can this be provided? Thank you 🙂

**Comment by ixjb94** [comment]
@thrik Hey,
save it as a .reg file
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Google\Chrome]
"ThirdPartyBlockingEnabled"=dword:00000000
```
example: chrome.reg

But i don't think it works, because chrome is not allowing injection anymore.
