### ISSUE TITLE
Viruses in the ForceBindIP.-.Gui

### ISSUE THREAD

**Issue by kalpakci** [mhasanjb/ForceBindIP-Gui#15]
Is there a reason why the executable contains so many viruses? 

Antiy-AVL Trojan[Downloader]/Autoit.Inetget.a
Bkav Pro W32.AIDetectMalware
McAfee-GW-Edition BehavesLike.Win32.TrojanAitInject.dh
SecureAge Malicious
SentinelOne (Static ML) Static AI - Malicious PE
VBA32 Trojan-Downloader.Autoit.gen

[see virus total report](https://www.virustotal.com/gui/file/8b5b2383bc7207516f60d6a1c72eacf3e1e15cb34eb8c6297755f7f1368346c1)

**Comment by ixjb94** [comment]
Hey @kalpakci .
you can see this Issue: https://github.com/ixjb94/ForceBindIP-Gui/issues/14 
![image](https://github.com/ixjb94/ForceBindIP-Gui/assets/121232430/aa9b4661-a288-4338-bfdd-5e484748c4a3)

**Comment by kalpakci** [comment]
Instead of downloading an .exe directly, you change it and we can host the file as a .zip or another archive format. After downloading, you can programmatically unzip the file and extract the .exe. This way, you're not directly downloading executable files. I am not this fill fix your warnings.
