### ISSUE TITLE
ip warn

### ISSUE THREAD

**Issue by cool-delete** [mhasanjb/ForceBindIP-Gui#16]
![image](https://github.com/ixjb94/ForceBindIP-Gui/assets/13638610/6b30eebf-22fd-476e-b229-4a89ea35fc6f)

**Comment by ixjb94** [comment]
@cool-delete Hi 😊,
In the upper select box, You should select your internet adapter.
Like this:
![image](https://github.com/ixjb94/ForceBindIP-Gui/assets/121232430/c7d6a1fd-2ed8-4b45-a60f-02f42a15de9d)
![image](https://github.com/ixjb94/ForceBindIP-Gui/assets/121232430/274767c3-f894-4042-88e4-274c8e37e94e)
