### ISSUE TITLE
[Request] Option to set default architecture x64/x86

### ISSUE THREAD

**Issue by DavidBevi** [mhasanjb/ForceBindIP-Gui#17]

**Comment by ixjb94** [comment]
Hi @DavidBevi

Added.    
you can download the new version.

[Dist](https://github.com/ixjb94/ForceBindIP-Gui/tree/main/dist)
or    
[Release](https://github.com/ixjb94/ForceBindIP-Gui/releases/tag/binary)
or    
[.exe File](https://github.com/ixjb94/ForceBindIP-Gui/releases/download/binary/ForceBindIP.-.Gui.exe)


## How to use:
You have two options:     

1- Delete the .ini (ForceBindIP-config.ini) file and reopen the app so it will create X section for you as well
(note it will delete your existing configs)    

2- Add X= to your existing .ini file    
So the file should be like this:    
Button1=Steam    
Address=c:\steam    
X=86 (or you can do 64)    

[Reference](https://github.com/ixjb94/ForceBindIP-Gui?tab=readme-ov-file#init)
