### ISSUE TITLE
Error with GUID: couldn't find named adapter

### ISSUE THREAD

**Issue by john371911** [mhasanjb/ForceBindIP-Gui#18]
Same as described in this. Also solved by the his method. Hope this app can fix this issue so both uppercase and lowercase work.
https://superuser.com/questions/1385468/forcebindip-couldnt-find-named-adapter

**Comment by ixjb94** [comment]
@john371911 Hi 🤗,
I'm not using Regedit Approach, instead WMI.
If you could provide an image of the Error, that would be amazing.
Also a reminder, this is a GUI not the forcebindip itself, but a GUI wrapper for it.

**Comment by john371911** [comment]
Oh, I didn't noticed the difference. I tried to use GUI but didn't work, so I simply used origin forceBindIP.
