### ISSUE TITLE
You know what need to be modify on Edge to get it to work?

### ISSUE THREAD

**Issue by ZeroCool22** [mhasanjb/ForceBindIP-Gui#4]
Chrome and FireFox have a workaround to get it to work with Forcebindip, but i didn't found anything about Edge.

**Comment by ghost** [comment]
Hi,
No i'm sorry, the only trick that i know is changing metrics.

**Comment by ZeroCool22** [comment]
> 
> 
> Hi,
> No i'm sorry, the only trick that i know is changing metrics.

Ok, no problem. Thx.
