### ISSUE TITLE
Can't get this to work & quick launch buttons result in error message

### ISSUE THREAD

**Issue by lucknaumann** [mhasanjb/ForceBindIP-Gui#5]
I get an error message when trying to launch a program from one of the "Quick Access" buttons (the program closes when clicking the message's "OK" button), and nothing happens when trying to launch a program from the "Run Application" button. 
**The error message reads:**
```
Line 4787 (File
“C\Ketarin\Internet\ForceBindlP-Gui-mhasanjb\ForceBindIP -
Gui_x64.exe"}:

Error: Array variable has incorrect number of subscripts or
subscript dimension range exceeded.
```

- I ran the "Download and Config ForceBindIP", which downloads the ForceBindIP zip and unzips it in the program's folder. After doing this it said the program is ready to be used. I mention this because I had installed ForceBindIP prior to finding this program and thought it would use the installed version.
- I changed/added some programs in the config.ini but even tried to launch the default "Quick Access" button for Firefox and still get the error message.
- This also happens when using the non-x64 version of this program.

_I noticed that this program is also missing the "-i" switch for "Delayed DLL injection"._

**Comment by mhasanjb** [comment]
@lucknaumann Hey thanks for the issue,
browser: firefox and chrome they wont let you inject 3rd party dll's anymore, so if you want to use chrome,firefox you need to use metric trick. [here](https://github.com/mhasanjb/ForceBindIP-Gui/issues/3#issuecomment-688056324).

quick access: after writing in config file, just close/open the app and then select x86 or x64 radio button, then click on the app thats it.
config example: 
[Button1]
Name=VLC
Address=C:\Program Files (x86)\VideoLAN\VLC\vlc.exe

-i parameter: i tested -i version, its totally fine to not using -i parameter.

**Comment by lucknaumann** [comment]
@mhasanjb Thanks for the quick response. I have not yet tried the metric trick (thanks for pointing that out) as I knew Chrome(ium) probably didn't have a workaround but wasn't sure if FF still did with that `about:config` setting (I hadn't looked). I will try it hopefully today and report back.

I tested the Quick Access with VLC in the way you describe and still get the error message.

I realized I didn't mention (but maybe you figured 😄 ) that I'm on Windows 10 (20H2, if that matters). Not sure why this isn't working... 

"-i" parameter: OK. Wasn't sure about that.

**Comment by mhasanjb** [comment]
@lucknaumann
i just downloaded the .exe file from github, it seems github broke the .exe file so i made .zip file and its working now.
just download the .zip file and extract it then run it (link available in repo).
[Download from here](https://github.com/mhasanjb/ForceBindIP-Gui/blob/master/ForceBindIP%20-%20Gui.zip)
or direct download from [here](https://raw.githubusercontent.com/mhasanjb/ForceBindIP-Gui/master/ForceBindIP%20-%20Gui.zip)
thanks for reporting ❤

**Comment by lucknaumann** [comment]
@mhasanjb You're welcome. 😁 
Thanks! It works now. Does it matter if it's not the x64, since there's an x64 .exe? Maybe putting them in the Releases section would help prevent corruption? Or even as zip files make it easier to download. Also, I haven't tried out the metric trick yet but will report if there's a problem with it.
