### ISSUE TITLE
Firefox 93.0 and ForceBindIP 1.32

### ISSUE THREAD

**Issue by RndUser0** [mhasanjb/ForceBindIP-Gui#7]
In Firefox 93.0, setting the preference "browser.launcherProcess.enabled" to "false" doesn't work. Do you have any idea on how to make ForceBindIP work with Firefox 93.0?

**Comment by RndUser0** [comment]
After trying some things it works again now.

**Comment by AdnanBen** [comment]
> After trying some things it works again now.

What did you try exactly? Having issues trying to use firefox with this, thanks.

**Comment by RndUser0** [comment]
I think, I just switched the preference "browser.launcherProcess.enabled" on the "about:config" page multiple times and restarted the browser after every change. The preference has to be set to "false" in the end. Also, one time my VPN network interface changed, so I had to change it in the command that runs Firefox with ForceBindIP.
